

#OC = Open Carry, NC = No Carry, CC = Concealed Carry
def getGunLaws():
    return {
        'AL' : 'OC',
        'AK' : 'CC',
        'AZ' : 'OC',
        'AR' : 'CC',
        'CA' : 'NC',
        'CO' : 'CC',
        'CT' : 'OC',
        'DC' : 'NC',
        'DE' : 'OC',
        'FL' : 'CC',
        'GA' : 'CC',
        'HI' : 'NC',
        'ID' : 'OC',
        'IL' : 'CC',
        'IN' : 'OC',
        'IA' : 'OC',
        'KS' : 'OC',
        'KY' : 'OC',
        'LA' : 'OC',
        'ME' : 'OC',
        'MD' : 'NC',
        'MA' : 'NC',
        'MI' : 'OC',
        'MN' : 'OC',
        'MS' : 'OC',
        'MO' : 'OC',
        'MT' : 'OC',
        'NE' : 'OC',
        'NV' : 'OC',
        'NH' : 'OC',
        'NJ' : 'NC',
        'NM' : 'OC',
        'NY' : 'NC',
        'NC' : 'OC',
        'ND' : 'OC',
        'OH' : 'OC',
        'OK' : 'OC',
        'OR' : 'OC',
        'PA' : 'OC',
        'RI' : 'NC',
        'SC' : 'CC',
        'SD' : 'OC',
        'TN' : 'OC',
        'TX' : 'OC',
        'UT' : 'OC',
        'VT' : 'OC',
        'VA' : 'OC',
        'WA' : 'OC',
        'WV' : 'OC',
        'WI' : 'OC',
        'WY' : 'OC'
    }

def getStates():
    states = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DC", "DE", "FL", "GA",
          "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD",
          "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ",
          "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC",
          "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY"]
    return states
